services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    init: true
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=miguel
      - N8N_BASIC_AUTH_PASSWORD=MtP070213.
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - TINI_SUBREAPER=1
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
    driver: local
